#!/usr/bin/env python3
"""
Generate 530 diverse Pauls to complete the 1000 Paul directory.
"""

# Diverse professions beyond just traders
diverse_professions = [
    # Arts & Creative
    ("Artist", "Creative", "Visual Trends"),
    ("Painter", "Intuitive", "Color Psychology"),
    ("Sculptor", "Patient", "3D Assets"),
    ("Musician", "Rhythmic", "Audio NFTs"),
    ("Composer", "Systematic", "Pattern Recognition"),
    ("Dancer", "Flow", "Movement Data"),
    ("Actor", "Adaptive", "Sentiment Analysis"),
    ("Director", "Visionary", "Project Management"),
    ("Writer", "Analytical", "Narrative Trends"),
    ("Poet", "Metaphorical", "Abstract Patterns"),
    ("Photographer", "Observant", "Visual Data"),
    ("Filmmaker", "Storytelling", "Media Trends"),
    ("Designer", "Aesthetic", "UX Patterns"),
    ("Architect", "Structural", "Spatial Analysis"),
    ("Fashionista", "Trendy", "Style Cycles"),
    
    # Science & Research
    ("Scientist", "Methodical", "Research"),
    ("Researcher", "Thorough", "Data Analysis"),
    ("Biologist", "Organic", "Bio Trends"),
    ("Chemist", "Precise", "Material Science"),
    ("Physicist", "Theoretical", "Quantum"),
    ("Astronomer", "Long-term", "Cosmic Cycles"),
    ("Geologist", "Historical", "Resource Patterns"),
    ("Meteorologist", "Predictive", "Weather Patterns"),
    ("Oceanographer", "Deep", "Marine Data"),
    ("Archaeologist", "Patient", "Historical Value"),
    ("Anthropologist", "Cultural", "Social Trends"),
    ("Sociologist", "Observant", "Group Behavior"),
    ("Psychologist", "Behavioral", "Mental Models"),
    ("Neuroscientist", "Complex", "Brain Data"),
    ("Geneticist", "Code", "DNA Patterns"),
    
    # Food & Culinary
    ("Chef", "Creative", "Flavor Trends"),
    ("Baker", "Precise", "Timing"),
    ("Butcher", "Traditional", "Supply Chains"),
    ("Sommelier", "Refined", "Vintage Value"),
    ("Barista", "Artisan", "Coffee Culture"),
    ("Brewmaster", "Fermentation", "Craft Trends"),
    ("Chocolatier", "Luxury", "Premium Goods"),
    ("Farmer", "Seasonal", "Agricultural"),
    ("Fisherman", "Patient", "Catch Timing"),
    ("Hunter", "Strategic", "Opportunity"),
    ("Forager", "Exploratory", "Wild Resources"),
    ("Winemaker", "Vintage", "Long Aging"),
    ("Distiller", "Concentrated", "Spirits"),
    ("Cheesemaker", "Aged", "Fermentation"),
    ("Beekeeper", "Colony", "Honey Markets"),
    
    # Sports & Athletics
    ("Athlete", "Disciplined", "Performance"),
    ("Runner", "Endurance", "Pace"),
    ("Swimmer", "Fluid", "Currents"),
    ("Cyclist", "Momentum", "Velocity"),
    ("Climber", "Strategic", "Risk Assessment"),
    ("Yogi", "Balanced", "Flexibility"),
    ("Fighter", "Aggressive", "Combat"),
    ("Diver", "Deep", "Pressure"),
    ("Skier", "Fast", "Slopes"),
    ("Surfer", "Wave", "Timing"),
    ("Golfer", "Precision", "Course Management"),
    ("Tennis", "Rally", "Back-and-Forth"),
    ("Boxer", "Counter", "Defense"),
    ("Gymnast", "Agile", "Rotation"),
    ("Rower", "Team", "Synchronization"),
    
    # Education & Knowledge
    ("Teacher", "Patient", "Education"),
    ("Professor", "Academic", "Research"),
    ("Librarian", "Organized", "Information"),
    ("Student", "Learning", "Growth"),
    ("Mentor", "Guiding", "Development"),
    ("Coach", "Motivating", "Performance"),
    ("Tutor", "Focused", "Skill Building"),
    ("Educator", "Enlightening", "Knowledge"),
    ("Philosopher", "Deep", "Wisdom"),
    ("Historian", "Contextual", "Cycles"),
    ("Linguist", "Semantic", "Language"),
    ("Mathematician", "Logical", "Numbers"),
    ("Statistician", "Probabilistic", "Data"),
    ("Logician", "Reasoning", "Proofs"),
    ("Theologian", "Faith", "Belief Systems"),
    
    # Trades & Crafts
    ("Carpenter", "Builder", "Construction"),
    ("Blacksmith", "Forging", "Metalwork"),
    ("Tailor", "Fitting", "Custom"),
    ("Jeweler", "Precise", "Valuables"),
    ("Potter", "Shaping", "Clay"),
    ("Weaver", "Interconnected", "Patterns"),
    ("Glassblower", "Heat", "Forming"),
    ("Leatherworker", "Durable", "Long-lasting"),
    ("Mechanic", "Repair", "Systems"),
    ("Electrician", "Current", "Power"),
    ("Plumber", "Flow", "Pipes"),
    ("Mason", "Stone", "Foundation"),
    ("Welder", "Fusion", "Joining"),
    ("Roofer", "Protection", "Coverage"),
    ("Painter", "Coverage", "Finish"),
    
    # Transportation & Travel
    ("Pilot", "Navigation", "Flight"),
    ("Captain", "Leadership", "Voyage"),
    ("Driver", "Control", "Route"),
    ("Sailor", "Wind", "Currents"),
    ("Astronaut", "Space", "Orbit"),
    ("Navigator", "Guidance", "Direction"),
    ("Explorer", "Discovery", "New Worlds"),
    ("Traveler", "Wandering", "Experience"),
    ("Guide", "Leading", "Paths"),
    ("Conductor", "Orchestrating", "Rail"),
    ("Engineer", "Design", "Systems"),
    ("Mechanic", "Fixing", "Machines"),
    ("Racer", "Speed", "Competition"),
    ("Cyclist", "Pedal", "Endurance"),
    ("Hiker", "Trail", "Journey"),
    
    # Nature & Outdoors
    ("Gardener", "Growth", "Cultivation"),
    ("Botanist", "Plant", "Flora"),
    ("Zoologist", "Animal", "Fauna"),
    ("Ranger", "Protection", "Conservation"),
    ("Forester", "Trees", "Woodland"),
    ("Ecologist", "Balance", "Ecosystem"),
    ("Conservationist", "Preservation", "Sustainability"),
    ("Veterinarian", "Care", "Animal Health"),
    ("Wildlife", "Natural", "Instinct"),
    ("Naturalist", "Observation", "Environment"),
    ("Geographer", "Mapping", "Territory"),
    ("Surveyor", "Measuring", "Land"),
    ("Prospector", "Seeking", "Resources"),
    ("Miner", "Extraction", "Underground"),
    ("Diver", "Underwater", "Depth"),
    
    # Public Service & Safety
    ("Firefighter", "Brave", "Emergency"),
    ("Police", "Protective", "Law"),
    ("Paramedic", "Responsive", "Medical"),
    ("Nurse", "Caring", "Health"),
    ("Doctor", "Healing", "Medicine"),
    ("Surgeon", "Precise", "Operations"),
    ("Dentist", "Oral", "Dental"),
    ("Pharmacist", "Dispensing", "Drugs"),
    ("Therapist", "Healing", "Mental"),
    ("Social Worker", "Supportive", "Community"),
    ("Judge", "Justice", "Law"),
    ("Lawyer", "Advocating", "Legal"),
    ("Detective", "Investigating", "Clues"),
    ("Spy", "Secret", "Intelligence"),
    ("Soldier", "Disciplined", "Military"),
    
    # Business & Commerce
    ("Merchant", "Trading", "Goods"),
    ("Shopkeeper", "Retail", "Sales"),
    ("Entrepreneur", "Startup", "Innovation"),
    ("Founder", "Building", "Companies"),
    ("CEO", "Executive", "Leadership"),
    ("Manager", "Organizing", "Teams"),
    ("Salesperson", "Persuasive", "Closing"),
    ("Marketer", "Promoting", "Brands"),
    ("Recruiter", "Talent", "Hiring"),
    ("Consultant", "Advising", "Strategy"),
    ("Accountant", "Counting", "Numbers"),
    ("Auditor", "Verifying", "Accuracy"),
    ("Banker", "Financial", "Money"),
    ("Lender", "Credit", "Loans"),
    ("Insurer", "Risk", "Coverage"),
    
    # Technology & Digital
    ("Coder", "Programming", "Software"),
    ("Developer", "Building", "Apps"),
    ("Hacker", "Exploiting", "Security"),
    ("Gamer", "Playing", "Virtual"),
    ("Streamer", "Broadcasting", "Live"),
    ("YouTuber", "Creating", "Video"),
    ("Influencer", "Social", "Following"),
    ("Blogger", "Writing", "Content"),
    ("Podcaster", "Talking", "Audio"),
    ("Vlogger", "Visual", "Diary"),
    ("Modder", "Modifying", "Games"),
    ("Miner", "Computing", "Crypto"),
    ("Staker", "Holding", "Yield"),
    ("Validator", "Verifying", "Blockchain"),
    ("Node", "Running", "Network"),
    
    # Entertainment & Performance
    ("Comedian", "Funny", "Humor"),
    ("Magician", "Illusion", "Tricks"),
    ("Juggler", "Balancing", "Multiple"),
    ("Clown", "Entertaining", "Circus"),
    ("Circus", "Performing", "Acrobatic"),
    ("DJ", "Mixing", "Beats"),
    ("Host", "Presenting", "Shows"),
    ("Anchor", "Reporting", "News"),
    ("Reporter", "Covering", "Stories"),
    ("Journalist", "Writing", "Articles"),
    ("Editor", "Refining", "Content"),
    ("Publisher", "Distributing", "Media"),
    ("Producer", "Creating", "Entertainment"),
    ("Agent", "Representing", "Talent"),
    ("Promoter", "Hyping", "Events"),
    
    # Spirituality & Philosophy
    ("Monk", "Meditative", "Zen"),
    ("Priest", "Spiritual", "Faith"),
    ("Rabbi", "Teaching", "Torah"),
    ("Imam", "Guiding", "Islam"),
    ("Guru", "Enlightening", "Wisdom"),
    ("Shaman", "Healing", "Ritual"),
    ("Mystic", "Mysterious", "Occult"),
    ("Prophet", "Foretelling", "Future"),
    ("Oracle", "Divining", "Prediction"),
    ("Seer", "Visionary", "Sight"),
    ("Astrologer", "Stellar", "Stars"),
    ("Tarot", "Card", "Reading"),
    ("Medium", "Channeling", "Spirits"),
    ("Healer", "Restoring", "Health"),
    ("Sage", "Wise", "Counsel"),
    
    # Miscellaneous
    ("Collector", "Accumulating", "Items"),
    ("Curator", "Selecting", "Art"),
    ("Appraiser", "Valuing", "Assets"),
    ("Auctioneer", "Selling", "Bidding"),
    ("Gambler", "Risking", "Betting"),
    ("Bookmaker", "Odds", "Wagering"),
    ("Pirate", "Plundering", "Treasure"),
    ("Ninja", "Stealth", "Shadow"),
    ("Samurai", "Honorable", "Warrior"),
    ("Knight", "Chivalrous", "Protection"),
    ("King", "Ruling", "Kingdom"),
    ("Queen", "Reigning", "Empire"),
    ("Duke", "Noble", "Estate"),
    ("Baron", "Wealthy", "Industry"),
    ("Mayor", "Governing", "City"),
]

# Generate markdown table
print("## Diverse Professionals (471-1000)\n")
print("| # | Name | Profession | Style | Specialty |")
print("|---|------|------------|-------|-----------|")

for i, (profession, style, specialty) in enumerate(diverse_professions[:530], start=471):
    print(f"| {i} | **{profession} Paul** | {profession} | {style} | {specialty} |")

print(f"\n<!-- Generated {len(diverse_professions[:530])} diverse Pauls -->")
